std="neovim"

[rules]
global_usage = "warn"
deprecated = "warn" # If changed to `allow` it will rely on `lua_ls` diagnostics.
multiple_statements = "allow"
incorrect_standard_library_use = "allow" # This is for cases like `string.format`, `package.config`, etc.
mixed_table = "allow"
unused_variable = "warn"
undefined_variable = "warn"
